version: "3.7"
services:
  app:
    container_name: app
    build: .
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  db:
    container_name: postgresql_db
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=prakhar.parashari
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=LibraryManagementSystem
    ports:
      - 5432:5432




